version: "3.8"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-app
    ports:
      - "4200:4200"
    volumes:
      - .:/app                # Mount toàn bộ mã nguồn vào container
      - /app/node_modules      # Tránh lỗi node_modules bị ghi đè
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge